### PR TITLE
fix docs build failing

### PR DESCRIPTION
**Pull request by CagtayFabry**
not sure why docs builds are failing suddenly so testing some older versions

### CODE REVIEW

**Comment by CagtayFabry** [comment]
seems like docutils 0.17 broke some things in the notebooks :/

**Comment by CagtayFabry** [comment]
The docs build is broken with the new `docutils` 0.17 so pinned to 0.16 for now to keep it running @vhirtham @marscher 

We should open an issue and look into it at some point, error messages can be seen in the Actions

**Review by marscher — APPROVED** [review]
Thanks for taking care of this. Has this already been reported upstream? So the problem is, that the titles of the notebooks are not being recognized, right?

**Comment by CagtayFabry** [comment]
> 
> 
> Thanks for taking care of this. Has this already been reported upstream? So the problem is, that the titles of the notebooks are not being recognized, right?

I did a quick google search but couldn't find anything so not sure
But I didn't dig into the problem either, maybe something is wrong with our notebook formatting? (I don't think so but who knows)

**Pull request merged**
