### PR TITLE
[doc] updated installing instructions

### PR DESCRIPTION
**Pull request by marscher**
## Changes

- Added note about how to obtain conda.
- Removed bamwelding conda-channel (we are on conda-forge now)

### CODE REVIEW

**Comment by CagtayFabry** [comment]
good catch, I only updated the `README.md` the last time

**Review by vhirtham — APPROVED** [review]

**Review by CagtayFabry — CHANGES_REQUESTED** [review]
can you update the `README.md` file as well and add the pip install command from there here? @marscher

**Comment by marscher** [comment]
Instructions are now in sync.

**Comment by CagtayFabry** [comment]
> Instructions are now in sync.

unfortunately the RST syntax for links doesn't display correctly for markdown

**Review by CagtayFabry — APPROVED** [review]

**Pull request merged**
