### PR TITLE
Download `single_pass_weld.wx` directly in the tutorials

### PR DESCRIPTION
**Pull request by vhirtham**
## Changes

I added a hidden cell at the top in each of the new tutorials. This cell calls the function to download the needed `single_pass_weld.wx` file. The background is that you can't run those tutorials locally without the file but it is only downloaded when in another directory if you actually build the docs. I also edit a flag to the download function to suppress text outputs.

## Checks

- [x] ~~updated CHANGELOG.rst~~
- [x] ~~updated tests~~
- [x] updated doc/
- [x] update example/tutorial notebooks
- [x] ~~update manifest file~~

### CODE REVIEW

**Comment by marscher** [comment]
I think we could also remove the download inside the docs (conf.py), right?

**Comment by CagtayFabry** [comment]
> I think we could also remove the download inside the docs (conf.py), right?

wasn't the idea to download the file once for the tests so that it is available?

**Comment by CagtayFabry** [comment]
I think it is cleaner to use the `"nbsphinx": "hidden"` cell metadata so that the download code doesn't show up in the html documentation

**Review by CagtayFabry — APPROVED** [review]

**Comment by marscher** [comment]
If the notebooks download the file, we do not need to do it explicitly (even for the tests), right? That should be the case as all notebook cells will be executed by the tests in sequential order. The only thing that could happen then is a race condition, when two notebooks will start to download the file. This should be avoided as it leads to unpredictable test failures. 
The current situation is, that we download during Sphinx building and only the first tutorial will download explicitly. 
The download code has been duplicated to do so. I'd prefer a solution without duplication and having the notebooks download it seems to be the one.

**Comment by CagtayFabry** [comment]
I just wasn't sure about the parallel execution of the notebooks via pytest but that's ok for me too if it works

**Comment by marscher** [comment]
not downloading in Sphinx works. The RTD error is unrelated. 
`
intersphinx inventory 'https://k3d-jupyter.org/objects.inv' not fetchable due to <class 'requests.exceptions.ConnectionError'>: HTTPSConnectionPool(host='k3d-jupyter.org', port=443): Max retries exceeded with url: /objects.inv (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe6e6f7c760>: Failed to establish a new connection: [Errno 110] Connection timed out'))
`

**Review by CagtayFabry — APPROVED** [review]

**Pull request merged**
