### PR TITLE
ignore matplotlib docs link warnings 

### PR DESCRIPTION
**Pull request by CagtayFabry**
## Changes
- ignore `matplotlib` link warnings in documentation

## Checks
- [x] updated doc/

### CODE REVIEW

**Comment by CagtayFabry** [comment]
failing weekly docs build for reference
https://github.com/BAMWelDX/weldx/actions/runs/1908741675

**Comment by CagtayFabry** [comment]
oh I was hoping this would fix the broken links but I guess not 😏

**Comment by CagtayFabry** [comment]
I think the problem is in the mpl docs structure, for example the `Axis` class is documented here https://matplotlib.org/stable/api/axes_api.html#the-axes-class but not like https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.html

**Comment by marscher** [comment]
https://github.com/BAMWelDX/weldx/runs/5357164230?check_suite_focus=true seems like we have two notebook jobs now, downloading the file (race condition, we were talking about).

**Pull request merged**
