### PR TITLE
Migrate from setup.cfg to pyproject.toml

### LINKED ISSUE #769: [setup.cfg] license_file parameter is deprecated, use license_files instead.
setuptools/config/setupcfg.py:459: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.

### PR DESCRIPTION
**Pull request by marscher**
## Changes

- All the metadata is now living in pyproject.toml
- setup.cfg is not needed anymore (just as a workaround to support editable/dev installs ATM).
- setup.py is not needed anymore
- Makes it mandatory to install weldx (source) with pip >= 20
- flake8 maintainer is currently refusing to rely upon pyproject.toml, as there is no std lib to parse (will available in Python 3.11). For this reason we move the cfg of flake8 to .flake8 (in order to leave setup.cfg) empty).

## TODOS
- [x] ~flake8 needs additional package to  https://stackoverflow.com/questions/64482562/specify-per-file-ignores-with-pyproject-toml-and-flake8~ revert settings to setup.cfg (until they decide to support it).
- [x] ~pytest-cov/coverage do not produce coverage data (combination step fails).~
- [x] ~ASDF entry points are not working (yet). Entrypoints are registered successfully. fixed pytest cfg section name.~
- [x] conda-build renders version to "None", seems like dynamically generated versions cannot be used at this stage. There used to be a similar problem for setup.py derived metadata back at the day. Raise issue at conda-build.

## Resources
- https://setuptools.pypa.io/en/latest/userguide/ shows syntax for pyproject.toml

## Related Issues

Closes #769, #754

## Checks

- [x] updated CHANGELOG.rst

### CODE REVIEW

**Comment by marscher** [comment]
https://github.com/conda/conda-build/pull/4480 is implemented, but not yet released (it seems).

**Comment by CagtayFabry** [comment]
> [conda/conda-build#4480](https://github.com/conda/conda-build/pull/4480) is implemented, but not yet released (it seems).

that feature would be a godsend.. should we wait for that release to merge?
I like the implementation with `pyproject.toml` here 👍

**Comment by marscher** [comment]
The conda-build containing the desired feature has been released, however it does not render the version correctly and is therefore not yet usable.

**Comment by CagtayFabry** [comment]
I think conda build 3.22 finally has what we need here https://github.com/conda/conda-build/releases/tag/3.22.0 🚀

**Review by CagtayFabry — APPROVED** [review]
I have tested the editable install without `setup.cfg` using `pip>=21.3` and `setuptools==65` as suggested here https://stackoverflow.com/a/69711730/11242411 and it works @marscher 

but I think it is good to keep the `setup.cfg` stub for now for compatibility

**Comment by marscher** [comment]
Thanks for reviewing this. What do you mean by "keeping the setup.cfg stub"? I mean by now it would only store redundant information, so I do not understand, what the benefit would be.

**Pull request merged**
