### PR TITLE
add & apply pyproject-fmt

### PR DESCRIPTION
**Pull request by CagtayFabry**
## Changes

_Describe changes in this PR_

## Related Issues

Closes # (add issue numbers)

## Checks

- [ ] updated CHANGELOG.rst
- [ ] updated tests
- [ ] updated doc/
- [ ] update example/tutorial notebooks
- [ ] update manifest file

### CODE REVIEW

**Comment by marscher** [comment]
great, it sorted everything :+1: As the file is basically a dictionary, there would be no need to sort it all. I used the same ordering as it used to be in setup.cfg.

Validation to a schema sounds great. Who is maintaining this schema? Earlier, potential problems about the file just popped out as setuptools warnings. This is a much better way.

**Comment by CagtayFabry** [comment]
> great, it sorted everything :+1: As the file is basically a dictionary, there would be no need to sort it all. I used the same ordering as it used to be in setup.cfg.
> 
> Validation to a schema sounds great. Who is maintaining this schema? Earlier, potential problems about the file just popped out as setuptools warnings. This is a much better way.

We can also do away with the sorting but I guess for future comparability it might be usefull

I haven't looked into the schema verification, just saw it pop up over at the asdf repo

**Comment by marscher** [comment]
I'd opt out sorting, as sometimes it might be useful to place keys logically next to each other (e.g. pairs of settings, which belong together, but have different section names).

**Comment by CagtayFabry** [comment]
> I'd opt out sorting, as sometimes it might be useful to place keys logically next to each other (e.g. pairs of settings, which belong together, but have different section names).

It don't think you can opt out of the sorting (but some keys also seem like manually sorted)

**Comment by marscher** [comment]
The tool also does not seem to handle comments, which is a bummer as I like to document this file a little bit.

**Comment by marscher** [comment]
So I'd just skip the formatting at all (PyCharm also does a good job in formatting it) and just use the validation.

**Comment by CagtayFabry** [comment]
> So I'd just skip the formatting at all (PyCharm also does a good job in formatting it) and just use the validation.

sounds good for now, the formatting also removes comments which is not ideal imo

**Comment by CagtayFabry** [comment]
I'll open a new PR for this

**Comment by CagtayFabry** [comment]
closing this for #841

**Pull request closed without merging**
