### PR TITLE
Include markdown readme in sphinx index

### LINKED ISSUE #406: copy README.md contents to index.rst

### PR DESCRIPTION
**Pull request by marscher**
## Changes

Include Readme and Changelog markdown files from repo root into the sphinx documentation. It uses the extension `m2r2` which converts the Md files into rst. 

## Related Issues

Closes #406

## Checks

- [x] updated doc/

### CODE REVIEW

**Review by CagtayFabry — APPROVED** [review]
LGTM 🧐

**Comment by marscher** [comment]
https://weldx--415.org.readthedocs.build/en/415/index.html The heading level of "Python API" should be the same as the ones in README.md.

And somehow the logo is not being displayed (firefox).

**Comment by marscher** [comment]
[weldx--415.org.readthedocs.build-1626170700058.log](https://github.com/BAMWelDX/weldx/files/6807934/weldx--415.org.readthedocs.build-1626170700058.log)
Seems like the logo is not shipped anymore.

**Comment by CagtayFabry** [comment]
> [weldx--415.org.readthedocs.build-1626170700058.log](https://github.com/BAMWelDX/weldx/files/6807934/weldx--415.org.readthedocs.build-1626170700058.log)
> Seems like the logo is not shipped anymore.

good catch !

**Comment by CagtayFabry** [comment]
> https://weldx--415.org.readthedocs.build/en/415/index.html The heading level of "Python API" should be the same as the ones in README.md.
> 
> And somehow the logo is not being displayed (firefox).

thought that was intended, I'll fix it
https://github.com/crossnox/m2r2#restrictions

**Comment by CagtayFabry** [comment]
> > [weldx--415.org.readthedocs.build-1626170700058.log](https://github.com/BAMWelDX/weldx/files/6807934/weldx--415.org.readthedocs.build-1626170700058.log)
> > Seems like the logo is not shipped anymore.
> 
> good catch !

the logo does get shipped but somehow the link get's set to `..../_static/_static/WelDX_notext.svg` instead of just `..../_static/WelDX_notext.svg` as before..., might be an issue with the current pydata theme

**Comment by CagtayFabry** [comment]
seems to be a sphinx issue introduced in `4.1`, see https://github.com/sphinx-doc/sphinx/issues/9438 https://github.com/sphinx-doc/sphinx/pull/9381

**Pull request merged**
