### PR TITLE
Third tutorial: geometry

### PR DESCRIPTION
**Pull request by vhirtham**
## Changes

Add the third tutorial. [Original PR](https://github.com/BAMWelDX/weldx/pull/579) was automatically closed. All suggestions have been addressed. I also needed to fix some of our `pint` decorators and some related internals because there was a problem in the originally out commented `k3d` plots. 

- add ``path`` option to `WeldxFile.info` and `WeldxFile.show_asdf_header`

## Checks

- [x] updated CHANGELOG.rst
- [x] ~~updated tests~~
- [x] updated doc/
- [x] update example/tutorial notebooks
- [x] ~~update manifest file~~

### CODE REVIEW

**Comment by vhirtham** [comment]
Seems like I missed something but `k3d` plots are now showing up in the RTD docs: 

https://weldx--681.org.readthedocs.build/en/681/tutorials/01_03_geometry.html

nice... have to adjust the text at those sections.

**Comment by vhirtham** [comment]
@marscher @CagtayFabry There is currently an import warning in all tutorials. If somebody already knows the solution, please let me know. Otherwise I have to investigate. See first cell here: https://weldx--681.org.readthedocs.build/en/681/tutorials/01_03_geometry.html

**Comment by CagtayFabry** [comment]
> @marscher @CagtayFabry There is currently an import warning in all tutorials. If somebody already knows the solution, please let me know. Otherwise I have to investigate. See first cell here: https://weldx--681.org.readthedocs.build/en/681/tutorials/01_03_geometry.html

good catch!
and interesting, I am not sure how to get rid of this warning or if we can flag both of our extensions versions (`0.1.0` from the release and `0.1.1` from current dev) as supported

**Comment by CagtayFabry** [comment]
I have added the `path` option in a simple form to `WeldxFile.info` and `WeldxFile.show_asdf_header` here for convenience @marscher @vhirtham

**Review by CagtayFabry — APPROVED** [review]
looks (and reads) really nice 👍 🚀

**Review by marscher — APPROVED** [review]

**Pull request merged**
