### PR TITLE
Use mamba

### PR DESCRIPTION
**Pull request by marscher**
## Changes

use the fast conda replacement mamba in CI services to speed up environment creation.

I will not create it as a draft, since I explicitly want to try it on Github actions

### CODE REVIEW

**Comment by marscher** [comment]
Appveyor fails importing mambas binary extension, upstream: https://github.com/mamba-org/mamba/issues/586

**Comment by marscher** [comment]
@vhirtham do you have a clue, why the other checks are still pending?

**Comment by vhirtham** [comment]
@marscher No clue. Also don't know if there is a function to restart the actions. Try recommitting.

**Comment by marscher** [comment]
I gave it a try. Let's see what happens :+1:

**Comment by marscher** [comment]
still no "luck"

**Review by CagtayFabry — APPROVED** [review]
nice use of `mambabuild` 👍

I haven't checked the travis/av run times but looks good to me :)

**Comment by CagtayFabry** [comment]
On a related note we should probably contact readthedocs to see if we can use the `CONDA_USES_MAMBA` flag (and maybe some others) to speed up docs build time

https://docs.readthedocs.io/en/stable/guides/feature-flags.html

**Comment by marscher** [comment]
I will check this RTD feature out. Thanks for reviewing!

**Review by vhirtham — APPROVED** [review]

**Comment by marscher** [comment]
> I will check this RTD feature out. Thanks for reviewing!

quote from https://docs.readthedocs.io/en/stable/guides/feature-flags.html#feature-flags
> A separate request can be made by contacting us via email to enable or disable one or more of these featured flags for a particular project.

So I guess one of you guys need to write them.

**Comment by CagtayFabry** [comment]
> So I guess one of you guys need to write them.

done, let's see what happens

**Comment by CagtayFabry** [comment]
latest docs builds now using mamba: https://readthedocs.org/projects/weldx/builds/13223120/ 🐍

**Pull request merged**
