### PR TITLE
[WeldxFile] fix show header in non interactive sessions

### PR DESCRIPTION
**Pull request by marscher**
## Changes
In non interactive sessions the output was not printed, but simply returned. This made it harder to write code running in different environments. Now WeldxFile.show_asdf_header() prints.

## Checks

- [x] updated CHANGELOG.md
- [x] updated tests
- [ ] updated doc/
- [ ] update example/tutorial notebooks

### CODE REVIEW

**Review by CagtayFabry — APPROVED** [review]
we can disable doctest for this example, I think this works well enough 👍

**Comment by CagtayFabry** [comment]
what do you think about using `asdf.info` for console outputs? @marscher 
https://asdf.readthedocs.io/en/al-503-document-2.8-features/asdf/features.html#rendering-asdf-trees

**Comment by marscher** [comment]
> what do you think about using `asdf.info` for console outputs? @marscher
> https://asdf.readthedocs.io/en/al-503-document-2.8-features/asdf/features.html#rendering-asdf-trees

Yes, that produces pretty output. I will stick to that and remove the doctest or think of another example. Thanks for your feedback!

**Comment by CagtayFabry** [comment]
> 
> 
> > what do you think about using `asdf.info` for console outputs? @marscher
> > https://asdf.readthedocs.io/en/al-503-document-2.8-features/asdf/features.html#rendering-asdf-trees
> 
> Yes, that produces pretty output. I will stick to that and remove the doctest or think of another example. Thanks for your feedback!

agreed, for a simple console output that is pretty nice
should be simple to get the full yaml style output simply using `print()` when desired

**Pull request merged**
