### PR TITLE
Revert "pin asdf<2.14"

### PR DESCRIPTION
**Pull request by marscher**
Reverts BAMWelDX/weldx#828

Wait until asdf-2.14.3 and re-run failed test jobs

### CODE REVIEW

**Comment by marscher** [comment]
the RTD build timed out.

**Comment by CagtayFabry** [comment]
I'm fine with releasing 0.6.3 just for this to get a clean slate :+1:
what do think @marscher ?

**Comment by marscher** [comment]
Did we release 0.6.2 with the asdf<2.14 pinning?

**Comment by CagtayFabry** [comment]
> Did we release 0.6.2 with the asdf<2.14 pinning?

No that was just >2.8

https://github.com/BAMWelDX/weldx/blob/a617b06eb3e6b30ae70969812991e253b21d7333/pyproject.toml#L39

**Pull request closed without merging**
