### PR TITLE
Use weldx-widgets to reduce dependencies of weldx

### LINKED ISSUE #746: move plotting features to `weldx-widgets`
The goal is to remove the following dependencies from `weldx`
- `matplotlib`
- `k3d`
- `graphviz`

### PR DESCRIPTION
**Pull request by marscher**
## Changes

Use weldx-widgets
- removed k3d and mpl backends, types,  colors, and tests.
- removed warning about experimental package usage.

## Related Issues

Closes #746 

## Checks

- [x] updated CHANGELOG.rst
- [x] updated tests

### CODE REVIEW

**Comment by marscher** [comment]
@vhirtham We have discussed the mypy issue #752 and all linting issues left in PR are unrelated to the changes made. So in my opinion this is ready to be merged.

**Comment by vhirtham** [comment]
@marscher yes, we should ignore the mypy issues for now. I will start a new PR soon. However, the other linter errors (deepsource) should be fixed. I had a look at the reported issue. If the behavior is intended, just place a corresponding comment to the line so that it is ignored by deepsource. It complains about an open call with an external reference.

**Comment by marscher** [comment]
> 

The code triggering this external open issue in  _clean_notebook is a private function intended to clean notebooks, but I think this function is only a developer util, so it should be moved outside of the main package.

**Review by vhirtham — APPROVED** [review]
LGTM

**Comment by vhirtham** [comment]
@marscher You can just silence the warning with `# skipcq:` + error code. For example `# skipcq: PYL-W0622`

**Pull request merged**
