### PR TITLE
remove legacy schemas and code

### LINKED ISSUE #520: remove CSM legacy code and schemas
- remove code in `tags/.../_legacy`
- remove legacy schemas
- update manifest
- remove legacy mapping

### PR DESCRIPTION
**Pull request by CagtayFabry**
## Changes

initial draft to remove legacy schema support and code

## Related Issues

Closes #520, #529

## Checks

- [x] updated CHANGELOG.rst
- [x] updated tests
- [x] update example/tutorial notebooks
- [x] update manifest file

### CODE REVIEW

**Comment by CagtayFabry** [comment]
just wanted to see if everything works (it does besides one test case that I forgot to adapt in the initial rework to `asdf://`)

we can leave this open till `0.6.0` or redo quickly once we get closer to finish that release

**Comment by CagtayFabry** [comment]
we should probably do a quick 0.5.2 release and can merge this after @marscher @vhirtham

**Review by vhirtham — APPROVED** [review]

**Review by marscher — APPROVED** [review]
Thanks for cleaning up this legacy mess!

I think we should start a repo with test files created with released versions to check we can still read them (or check for expected failures).

**Comment by CagtayFabry** [comment]
> Thanks for cleaning up this legacy mess!
> 
> I think we should start a repo with test files created with released versions to check we can still read them (or check for expected failures).

that sounds like a really good idea 👍

**Pull request merged**
