### PR TITLE
update to python 3.9

### LINKED ISSUE #216: move to python 3.9 as default
I would like to transition to 3.9 featureset early, mostly because of the new dict operators (more user friendly)
https://docs.python.org/3/whatsnew/3.9.html#dictionary-merge-update-operators

we should also try support for the new type hints
https://docs.python.org/3/whatsnew/3.9.html#type-hinting-generics-in-standard-collections

### PR DESCRIPTION
**Pull request by CagtayFabry**
## Changes
Test py 3.9 as minimum version

## Related Issues
Closes #216 

## Checks
- [x] updated CHANGELOG.md
- [x] updated tests
- [x] updated doc/
- [x] update example/tutorial notebooks

### CODE REVIEW

**Comment by CagtayFabry** [comment]
waiting to test the binder build for this branch

**Comment by CagtayFabry** [comment]
> waiting to test the binder build for this branch

Branch runs fine on binder with `ipympl`
However since this is JupyterLab3 `k3d` only works in the classic notebook interface for now. Let's hope this get's updated soon

**Comment by CagtayFabry** [comment]
tracking RTD build support for python 3.9 via https://github.com/readthedocs/readthedocs.org/issues/7554

**Review by vhirtham — APPROVED** [review]

**Comment by vhirtham** [comment]
> However since this is JupyterLab3 k3d only works in the classic notebook interface for now. Let's hope this get's updated soon

Even though the lab interface is nicer, we can also run the classic interface on binder until k3d has better jupyter-lab support.

**Comment by CagtayFabry** [comment]
> > However since this is JupyterLab3 k3d only works in the classic notebook interface for now. Let's hope this get's updated soon
> 
> Even though the lab interface is nicer, we can also run the classic interface on binder until k3d has better jupyter-lab support.

yes it would be nice if k3d works in the notebooks directly without switching interface
It's a bit limiting because one has to pin `ipympl` & `matplotlib` version carefully (i think) to still work with jupyterlab2 (testing if this works with py39)

**Review by marscher — APPROVED** [review]
LGTM

**Pull request merged**
