### PR TITLE
Sphinx use myst-nb

### LINKED ISSUE #745: move documentation style to MyST
move from rST based to MyST base sphinx

https://myst-parser.readthedocs.io/en/latest/

### PR DESCRIPTION
**Pull request by marscher**
## Changes
- Sphinx uses myst-nb to directly include Markdown.
- moved tutorials to doc/src/ and removed copying code.
- Converted all remaining documents to MD.
- Notebooks gets executed myst-nb

### TODOs
- add prologue to notebook processing.
- fix: skipping unknown output mime type: application/json [mystnb.unknown_mime_type] https://github.com/executablebooks/MyST-NB/issues/464
- fix: weldx/transformations/__init__.py:docstring of weldx.transformations.CoordinateSystemManager:1: WARNING: unknown document: 'tutorials/transformations_02_coordinate_system_manager'
- fix: weldx/transformations/__init__.py:docstring of weldx.transformations.LocalCoordinateSystem:1: WARNING: unknown document: 'tutorials/transformations_01_coordinate_systems'

## Related Issues

Closes #745 

## Checks

- [x] updated CHANGELOG.rst
- [ ] updated tests
- [x] updated doc/
- [ ] update example/tutorial notebooks
- [ ] update manifest file

### CODE REVIEW

**Comment by marscher** [comment]
Readthedocs is failing, because it cannot find conf.py (we moved that to doc/src/) and it then falls back to an autogenerated one.

**Comment by CagtayFabry** [comment]
> Readthedocs is failing, because it cannot find conf.py (we moved that to doc/src/) and it then falls back to an autogenerated one.

The GH actions complains as well
```
Configuration error:
config directory doesn't contain a conf.py file (/home/runner/work/weldx/weldx/doc)
Error: Process completed with exit code 2.
```

**Comment by marscher** [comment]
> Readthedocs is failing, because it cannot find conf.py (we moved that to doc/src/) and it then falls back to an autogenerated one.

There is a setting in the admin interface of RTD, but it seemed to be ignored :hankey:

**Comment by marscher** [comment]
rtd installs an old version of docutils (0.17), which makes the build fail. I'll try to pin to >0.19

**Comment by CagtayFabry** [comment]
begone RST 🧙 👍

**Comment by marscher** [comment]
:rofl: in fact autosummary/autodoc still uses RST a lot. But at least we do not have to write it our self any more.

**Pull request merged**
