### PR TITLE
add issue and PR directives for sphinx

### PR DESCRIPTION
**Pull request by CagtayFabry**
format as seen in the xarray docs but we can adopt to a different style, I like the idea though

result: https://weldx--658.org.readthedocs.build/en/658/changelog_link.html

## Changes

- links issues/PRs in sphinx with specific code directive 

## Checks

- [x] updated CHANGELOG.rst
- [x] updated doc/

### CODE REVIEW

**Comment by CagtayFabry** [comment]
let me know what you think of this format @vhirtham @marscher 🚀

**Comment by vhirtham** [comment]
> let me know what you think of this format @vhirtham @marscher 🚀

This is really nice 👌 . Couldn't remember the rst link syntax and c&p'd them every time. This one is rather easy to memorize. 😉

**Review by vhirtham — APPROVED** [review]

**Review by marscher — APPROVED** [review]
That one will make our lives easier (will now write changelog entries like crazy) :)

Thank you!

**Comment by CagtayFabry** [comment]
> That one will make our lives easier (will now write changelog entries like crazy) :)
> 
> Thank you!

sadly `rstfmt` doesn't work with this because it doesn't know the directive
oh well, it was fun while it lasted 🤷‍♂️ 

(you can go back to 2 spaces now as well)

**Pull request merged**
