### PR TITLE
update to pint >=0.18

### PR DESCRIPTION
**Pull request by CagtayFabry**
## Changes
- bump to pint 0.18
- update pint related type hints

## Related Issues

Closes # (add issue numbers)

## Checks

- [x] updated CHANGELOG.rst
- [x] updated tests

### CODE REVIEW

**Comment by CagtayFabry** [comment]
I run into some issues correctly building the documentation when using the `pint._typing` module so switched back to providing some simple definitions for `UnitLike` and `QuantityLike`

The deepsource issues can be ignored on this one

**Comment by vhirtham** [comment]
> The deepsource issues can be ignored on this one

Would still prefer if we can ignore them explicitly using the designated comment like `# skipcq: PYL-W0613` instead of just keep piling them up.

**Review by vhirtham — APPROVED** [review]

**Comment by CagtayFabry** [comment]
> > The deepsource issues can be ignored on this one
> 
> Would still prefer if we can ignore them explicitly using the designated comment like `# skipcq: PYL-W0613` instead of just keep piling them up.

sure, feel free to add where appropriate

**Comment by vhirtham** [comment]
> > > The deepsource issues can be ignored on this one
> > 
> > 
> > Would still prefer if we can ignore them explicitly using the designated comment like `# skipcq: PYL-W0613` instead of just keep piling them up.
> 
> sure, feel free to add where appropriate

Done

**Pull request merged**
