### PR TITLE
add  `Δ°` pint preprocessor

### PR DESCRIPTION
**Pull request by CagtayFabry**
## Changes
- add text preprocessor for handling `Δ°` in unit notation

I have tested it for  `Δ°C`, `Δ°F` and `Δ°Re` but I think we should stick to the long serialization format for now @marscher @vhirtham

### CODE REVIEW

**Comment by marscher** [comment]
I'm just curios why this preprocessor is mandatory, if we do not even request to export a "delta" unit in the first place.

**Comment by CagtayFabry** [comment]
> I'm just curios why this preprocessor is mandatory, if we do not even request to export a "delta" unit in the first place.

just for convenience so we can use e.g. `Q_(150, "Δ°C")` since the default format everywhere outside of serialization is still 'short' so `Δ°` might still pop up in console outputs, plots etc.

**Comment by marscher** [comment]
Shouldn't we add a test for preprocessors? I think at least the delta case is not covered yet.

**Comment by CagtayFabry** [comment]
> Shouldn't we add a test for preprocessors? I think at least the delta case is not covered yet.

good idea, I will integrate it in one of the other testcases

**Comment by CagtayFabry** [comment]
please note the changes I made to unit checking in `weldx/tests/test_core.py` @vhirtham 
using `.is_compatible_with` for unit checking looks the most straight forward to me

**Review by vhirtham — APPROVED** [review]

**Pull request merged**
