### PR TITLE
Fix is jlab session

### LINKED ISSUE #846: [docs] WeldxFile output in notebooks renders to IPython.display.JSON in jupyterhub environment
This can only be shown in a Jupyter lab environment. So the selection of the output should be made aware, that it is contained in a Sphinx/non-interactive session in order to avoid this.

  
image

### PR DESCRIPTION
**Pull request by marscher**
## Changes
To detect a Jupyter lab server started by Jupyter Hub, we also inspect the parent processes environment.

## Related Issues

Closes #846 

## Checks

- [x] updated CHANGELOG.rst

### CODE REVIEW

**Comment by marscher** [comment]
Damn, this then breaks the doc building again, because we have api keys set for the ipykernel communication...

**Comment by CagtayFabry** [comment]
> Damn, this then breaks the doc building again, because we have api keys set for the ipykernel communication...

seems tricky..
we could also introduce some kind of flag to disable JSON output altogether for the sphinx build (or simply monkeypatch the behavior we want in the sphinx run)

**Comment by marscher** [comment]
I was wrong (probably looking at an outdated local build of the docs). Here it looks fine: https://weldx--854.org.readthedocs.build/en/854/tutorials/weldxfile.html
I've also tested the patched version on our Jupyterhub server and it shows the JSON output there.

**Comment by CagtayFabry** [comment]
> I was wrong (probably looking at an outdated local build of the docs). Here it looks fine: https://weldx--854.org.readthedocs.build/en/854/tutorials/weldxfile.html I've also tested the patched version on our Jupyterhub server and it shows the JSON output there.

yes it seems to work now, great 🚀 !

**Review by CagtayFabry — APPROVED** [review]

**Pull request merged**
