### PR TITLE
Use micromamba in Github workflows

### PR DESCRIPTION
**Pull request by marscher**
## Changes

the miniconda action takes almost 3 minutes to setup mamba itself. So we switch to a preinstalled version of mamba.

### CODE REVIEW

**Comment by CagtayFabry** [comment]
since the setup with readthedocs and conda-forge is now quite stable I think we can also remove the final 3 steps of the build process (`set package file env`, `actions/upload-artifact@v2`, `upload releases to dev label on Anaconda Cloud`) for the conda build workflow @marscher 👍

**Comment by marscher** [comment]
nice, that would simplify things a lot.

**Comment by marscher** [comment]
The rtd_environment.yaml installs weldx in development mode via a relative path. However this does not seem to work within the Github action, because the working directory is outside of the source/working copy (but in the $HOME/micromamba/envs dir). I've opened up an issue upstream.

**Review by CagtayFabry — APPROVED** [review]

**Comment by CagtayFabry** [comment]
setup seems pretty fast now 🚀

**Comment by marscher** [comment]
The only thing missing for a fast doc building is to use multiple sphinx jobs #508

**Comment by CagtayFabry** [comment]
wondering why the pytest run is missing here 🤔

**Pull request merged**
