### PR TITLE
groove schema refactor

### LINKED ISSUE #131: refactor ASDF groove schemas
Split up and reorganize current and future groove definitions

- setup top level `groove` tag, example schema layout:
    ```yaml
    "tag:weldx.bam.de:weldx/groove/iso_9692_1-1.0.0/terms" # definitions
    "tag:weldx.bam.de:weldx/groove/iso_9692_1-1.0.0/SingleVGroove"
    "tag:weldx.bam.de:weldx/groove/iso_9692_1-1.0.0/DoubleVGroove"
    "tag:weldx.bam.de:weldx/groove/iso_9692_1-1.0.0/HVGroove"
    ...
    ```
  or with versions at single grooves
    ```yaml
    "tag:weldx.bam.de:weldx/groove/iso_9692_1_2012/terms-1.0.0" # definitions
    "tag:weldx.bam.de:weldx/groove/iso_9692_1_2012/SingleVGroove-1.0.0"
    "tag:weldx.bam.de:weldx/groove/iso_9692_1_2012/DoubleVGroove-1.0.0"
    "tag:weldx.bam.de:weldx/groove/iso_9692_1_2012/HVGroove-1.0.0"
    ...
    ```

- add all tag names to `GrooveType` class
- dynamically generate `tag` in `GrooveType`
- use `tag` instead of `$ref`

### PR DESCRIPTION
**Pull request by CagtayFabry**
## Changes
Demo implementation of reworked groove schema layout

### ToDos
- [x] move groove code away from tags
  - maybe `weldx.welding.grooves` ?
- [x] move terms schema to top level

## Related Issues
Closes #131 

## Checks
- [x] updated CHANGELOG.md
- [x] updated tests
- [x] updated doc/
- [x] update example/tutorial notebooks

#### before
- a single file for all groove types (+ definitions)
- 👍 simple version handling (only one file)
- 👎 hard to see differences between versions (?)
- 👎 groove type listed in property (no direct link to ASDF classes)
- 👎 very hard to "understand" without ASDF knowledge
- 👎 documentation output not really helpful [link](https://weldx.readthedocs.io/en/latest/generated/weldx.bam.de/weldx/core/iso_groove-1.0.0.html)

#### after
- single schema file for each groove
- a top level definitions file to reference in other files
- 👍 simpler and cleaner documentation for each groove [example](https://weldx--181.org.readthedocs.build/en/181/generated/weldx.bam.de/weldx/groove/iso_9692_1/VGroove-1.0.0.html)
- 👍 easier to navigate files
- 👍 cleaner distinction between standards (and different versions?)
- 👍 a single tag for each groove can be implemented (see below)
- 👎 Versioning more complex? More files? Changes between revisions of the standards?

### moving groove classifications from properties to the `tag` 
previous:
```yaml
test_v_groove: !<tag:weldx.bam.de:weldx/core/iso_groove-1.0.0>
  type: SingleVGroove
  components:
    alpha: !unit/quantity-1.1.0 {unit: degree, value: 55}
    b: !unit/quantity-1.1.0 {unit: millimeter, value: 2}
    c: !unit/quantity-1.1.0 {unit: millimeter, value: 1}
    code_number: ['1.3', '1.5']
    t: !unit/quantity-1.1.0 {unit: centimeter, value: 1}
...
```
new:
```yaml
v_groove: !<tag:weldx.bam.de:weldx/groove/iso_9692_1/VGroove-1.0.0>
  t: !unit/quantity-1.1.0 {unit: millimeter, value: 9}
  alpha: !unit/quantity-1.1.0 {unit: degree, value: 50}
  b: !unit/quantity-1.1.0 {unit: millimeter, value: 2}
  c: !unit/quantity-1.1.0 {unit: millimeter, value: 4}
  code_number: ['1.3', '1.5']
```
- 👍 this should play nice with new "glob" tag syntax in `ASDF v2.8`
  - example: allow all ISO defined V-Grooves: `tag: "tag:weldx.bam.de:weldx/groove/iso_9692_1_*/VGroove-*`

#### Scenario 1
If we implement the ISO standard version/release year on a directory level like `tag:weldx.bam.de:weldx/groove/iso_9692_1_2012/VGroove-1.0.0`, `tag:weldx.bam.de:weldx/groove/iso_9692_1_2020/VGroove-1.0.0` how would we release new schema files for the grooves?
- Copy every schema file witha new tag (contents revised where necessary)
- we cannot use `$ref` or `tag` to reference old schemas (or can we?? -> seems we **cannot**, see #187 ) because we need a new tag (can we trick around here somehow?)

### code changes
- there are no more "string" groove names or defintions! Everything handled dynamically via classnames

### automatically link groove subtypes to base ASDF type
- should this be done via parent class or listing of all subclasses?
- how does ASDF handle this? Does ASDF create list of subclasses?
- listing all subclasses (+ parent class) would provide more information to the ASDF Extension

### groove ASDF type builds tags from class names
- accomplished using `to_tree_tagged()` implementation
https://github.com/BAMWelDX/weldx/blob/68917c1f1646bcad687c518a83db7f48135769d2/weldx/asdf/tags/weldx/groove/iso_9692_1.py#L653-L687

### implement `__post_init__` function
- before it was possible to create some "invalid" python groove objects (passing "None"). This was at least detected/caught at ASDF level or in the `groove.plot()` function
- parameters/properties that depend on other other parameters now are be implemented with the `__post_init__`function:
https://github.com/BAMWelDX/weldx/blob/68917c1f1646bcad687c518a83db7f48135769d2/weldx/asdf/tags/weldx/groove/iso_9692_1.py#L555-L562
- we could als do more math sanity checks (and determine `code_number`) here
- very cool funciton with `dataclasses` !

### rework `get_groove` function
- before this was a manual call with the right parameter mapping to specific groove classes
- mapping moved to the class definitions
https://github.com/BAMWelDX/weldx/blob/f1b8fb6533ba9f1fd185b7777ce8425ec6c6ad23/weldx/asdf/tags/weldx/groove/iso_9692_1.py#L55-L86
- `get_groove` code is now very simple
https://github.com/BAMWelDX/weldx/blob/f1b8fb6533ba9f1fd185b7777ce8425ec6c6ad23/weldx/asdf/tags/weldx/groove/iso_9692_1.py#L924-L935
- update `get_groove` docstring format (now much nice on sphinx build [link](https://weldx--181.org.readthedocs.build/en/181/_autosummary/weldx.asdf.tags.weldx.groove.iso_9692_1.get_groove.html#weldx.asdf.tags.weldx.groove.iso_9692_1.get_groove) )

### CODE REVIEW

**Comment by CagtayFabry** [comment]
this should be ready now @vhirtham @mark141
a few edge cases when generating profiles from grooves are not covered in the examples (hence coverage decrease)

**Review by vhirtham — APPROVED** [review]
Just skimmed over the content of `iso_9692_1.py` and didn't see anything suspicious. The rest looks fine.

**Comment by CagtayFabry** [comment]
> Just skimmed over the content of `iso_9692_1.py` and didn't see anything suspicious. The rest looks fine.

what do you think about the new file layout?
- regarding ASDF groove schema files
- python files (separation ASDF-`tag` code  in `weldx.asdf.tags` from module implementation of the `Groove` classes in `weldx.welding`)
- import order in `__init__.py`

**Comment by vhirtham** [comment]
> regarding ASDF groove schema files

Do you mean that they are in the directory ´groove/iso_9692_1_2013_12´? That should be fine for now. As discussed last week, we should see how to handle changes in the norm and reevaluate the folder and file structure if necessary. 

> python files (separation ASDF-tag code in `weldx.asdf.tags` from module implementation of the Groove classes in `weldx.welding`)

This is nice and I think we should generally keep doing this with all classes (exept some serialization helpers). As far as I can remember this should be the case for the other classes and the grooves were an exception, but I am not 100% sure :)

> import order in `__init__.py`

Saw that you disabled isort (`isort:skip_file`). Thought the reason was just to separate the imports by the purpose of the modules, which is fine for me. But apart from adding some visual separation, there shouldn't be any effect, right? However, after taking a closer look, this line is a little bit confusing to me: `import weldx.utility  # import this first to avoid circular dependencies`. Didn't know that circular dependencies are that much of a problem in Phython.

**Comment by CagtayFabry** [comment]
> > import order in `__init__.py`
> 
> Saw that you disabled isort (`isort:skip_file`). Thought the reason was just to separate the imports by the purpose of the modules, which is fine for me. But apart from adding some visual separation, there shouldn't be any effect, right? However, after taking a closer look, this line is a little bit confusing to me: `import weldx.utility # import this first to avoid circular dependencies`. Didn't know that circular dependencies are that much of a problem in Phython.

Yeah I ran into some issues when importing when importing `weldx.core` first. Maybe we have to do some cleanup at some point.
But it could also have been because some weldx core code was used in the asdf tag section (which created a lot of circular imports)

**Comment by vhirtham** [comment]
> Yeah I ran into some issues when importing when importing weldx.core first. Maybe we have to do some cleanup at some point. But it could also have been because some weldx core code was used in the asdf tag section (which created a lot of circular imports)

Maybe we should keep this on the radar (create an issue). The order of imports should be irrelevant, but we can fix this later

**Review by mark141 — APPROVED** [review]
All yaml schemas look good and the reorganization is clearer.

If not done yet: add the issue for the `to_profile` changes.

**Pull request merged**
