### PR TITLE
Separate transformation tests

### PR DESCRIPTION
**Pull request by vhirtham**
## Changes

Separate the tests for the transformation classes into their own files

### CODE REVIEW

**Comment by vhirtham** [comment]
This also makes the wrapping test classes (`TestLocalCoordinateSystem` etc) obsolete. What do you think @CagtayFabry

**Comment by CagtayFabry** [comment]
certainly looks a lot more manageable 👍 (I tried editing the `test_transformations` in GitHub web a few days ago, 4000 lines was hard to handle 😄 )

I guess also move CSM test into a separate file in that subfolder?

**Comment by vhirtham** [comment]
> certainly looks a lot more manageable 👍 (I tried editing the `test_transformations` in GitHub web a few days ago, 4000 lines was hard to handle 😄 )
> 
> I guess also move CSM test into a separate file in that subfolder?

Already on it. I just wanted to know if you think that we should remove those wrapper classes 😉

**Comment by vhirtham** [comment]
Removed the extra classes. This should be good to go.

**Review by CagtayFabry — APPROVED** [review]

**Pull request merged**
