### PR TITLE
v0.6.5

### PR DESCRIPTION
**Pull request by CagtayFabry**
Unfortunately the initial changes slipped past on master here 700850d21970dadb7dfbd893eecf58c91ab86434

## Changes

- drop Python 3.8
- drop Python 3.9
- update minimum scipy and networkx versions

## create release PR

- [x] create a PR that finalizes the code for the next version
  - [x] name the PR according to the version `vX.Y.Z` and add the `release`
    tag ([example here](https://github.com/BAMWelDX/weldx/pull/419))
  - [x] make sure `CHANGELOG.md` is up-to-date and enter current date to the release version
  - [x] add summarized release highlights where appropriate
  - [x] update the `CITATION.cff` version number and date
  - [x] search the project for `deprecated` and remove deprecated code
- [ ] wait for review and the CI jobs to finish
- [ ] check the readthedocs PR build

## Merge the Pull Request

- [ ] merge normally and wait for all CI actions to finish on the main branch

## add Git(hub) tag

- [ ] tag and release the current master version on GitHub using the **Releases** feature
  - [ ] name the release **git tag** according to the version released (e.g. **v0.3.3**)
  - [ ] name the GitHub release accordingly, omitting the **v** prefix (this can be change later so don't worry, in
    doubt use **vX.Y.Z** everywhere)
  - [ ] copy the changes/release notes of the current version into the description and change the GitHub PR links to GitHub markdown
- [ ] wait for all Github Actions to finish

## ReadTheDocs updates

- [ ] check the build processes for `latest`, `stable` and `vX.Y.Z` get triggered on RTD (the tag build can get
  triggered twice, resulting in a failed/duplicated build, no need to worry)

## pypi release

- [ ] check the automatic release to pypi after the `build` action completes [here](https://pypi.org/project/weldx/)

## conda-forge release

- pypi release should get picked up by the conda-forge bot and create the new
  pull-request [here](https://github.com/conda-forge/weldx-feedstock/pulls)
- [ ] carefully check the `meta.yaml` in the pull request, manually update all changes in the build and run dependencies
- [ ] merge with 2 or more approved reviews

### CODE REVIEW

**Comment by CagtayFabry** [comment]
Python 3.9 seems to run into an issue with the `fs` package in our test suite https://github.com/BAMWelDX/weldx/actions/runs/4626993379/jobs/8184371412

I could reproduce the error locally but I am nut sure what caused it, Python 3.10 seems to work again for some reason

**Comment by marscher** [comment]
I've seen this error before. It looks like the given path for the Quality standard is None. So it is not an issue with Python 3.9, but our code.

**Comment by CagtayFabry** [comment]
> I've seen this error before. It looks like the given path for the Quality standard is None. So it is not an issue with Python 3.9, but our code.

yes but it only appears with 3.9 (at least for me)
Anyway, `fs` seems rather unmaintained and is running into quite a few deprecation warnings, maybe we should try to find an alternative way (using `asdf` tools)

**Comment by marscher** [comment]
the fewer dependencies the fewer points of failure. If asdf.tools provides a an alternative why not use it.

**Pull request closed without merging**
